export const projects = [
    {
        id: 1,
        name: "React & TS Shop",
        category: "React & Ts",
        img: "images/project1.jpg",
        gitLink: "https://github.com/Bashir-Alansary/You-Me-Shop.git",
        viewLink: "https://animated-toffee-68e83d.netlify.app",
    },
    {
        id: 2,
        name: "ZayInvestment",
        category: "JQuery",
        img: "images/project2.jpg",
        gitLink: "https://github.com/Bashir-Alansary/Zay-Investment.git",
        viewLink: "https://gregarious-liger-2a9a34.netlify.app",
    },
    {
        id: 3,
        name: "React Shop",
        category: "React",
        img: "images/project3.jpg",
        gitLink: "https://github.com/Bashir-Alansary/React-Store.git",
        viewLink: "https://delightful-croquembouche-1c2d5d.netlify.app",
    },
    {
        id: 4,
        name: "React 15 Projects",
        category: "React",
        img: "images/project4.jpg",
        gitLink: "https://github.com/Bashir-Alansary/React-15-Projects.git",
        viewLink: "https://clever-cuchufli-850e28.netlify.app",
    },
    {
        id: 5,
        name: "Medical Services",
        category: "JQuery",
        img: "images/project5.jpg",
        gitLink: "https://github.com/Bashir-Alansary/Medical-Services.git",
        viewLink: "https://github.com/Bashir-Alansary/Medical-Services.git",
    },
    {
        id: 6,
        name: "Bakery App",
        category: "React",
        img: "images/project6.jpg",
        gitLink: "https://github.com/Bashir-Alansary/Bakery.git",
        viewLink: "https://github.com/Bashir-Alansary/Bakery.git",
    },
    {
        id: 7,
        name: "ZayInvestment Account",
        category: "JQuery",
        img: "images/project7.jpg",
        gitLink: "https://github.com/Bashir-Alansary/Zay-Investment.git",
        viewLink: "https://reliable-klepon-412be7.netlify.app",
    },
    {
        id: 8,
        name: "Pharmacy App",
        category: "Html & CSS",
        img: "images/project8.png",
        gitLink: "https://github.com/Bashir-Alansary/Pharmacy.git",
        viewLink: "https://github.com/Bashir-Alansary/Pharmacy.git",
    },
];